name: Build and push image for Gitainer

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        name: Check out code

      - name: Build Test Image
        run: docker build -f packages/gitainer/Dockerfile.test -t gitainer-test .

      - name: Run Tests
        run: docker run --privileged --rm -w /app gitainer-test

  build-publish-github:
    needs: test
    uses: martin/chromart-gitea-actions/.gitea/workflows/docker-publish-ghcr@main
    with:
      image_name: ghcr.io/martindmtrv/gitainer
      file: packages/gitainer/Dockerfile
      platforms: linux/amd64,linux/arm64
