name: Build and push image for Gitainer

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        name: Check out code

      - name: Build Docker image
        run: docker buildx build . -t 192.168.1.150:9120/gitainer:latest

      - name: Push Docker image to local repo
        run: docker image push --all-tags 192.168.1.150:9120/gitainer:latest