name: Build and push image for Gitainer

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        name: Check out code

      - name: Build Test Image
        run: docker build -f Dockerfile.test -t gitainer-test .

      - name: Run Tests
        run: docker run --privileged --rm -v ./:/app -w /app gitainer-test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: gitea.chromart.cc
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            gitea.chromart.cc/martin/gitainer:v1
            gitea.chromart.cc/martin/gitainer:latest
