#! fragments/common.yaml
services:
  app:
    <<: *common
    image: alpine:latest
    command: sleep infinity
    stop_grace_period: 1s
    labels:
      gitainer.identifier: web
      caddy: app.${DOMAIN}
      app.sentry-dsn: ${SENTRY_DSN}
  worker:
    <<: *common
    image: alpine:latest
    command: sleep infinity
    stop_grace_period: 1s
    labels:
      gitainer.identifier: jobs
    environment:
      CACHE_URL: redis://:${CACHE_PASSWORD}@cache:6379
      LOG_LEVEL: ${LOG_LEVEL:-info}
